/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as TinkoffRouteImport } from './routes/tinkoff'
import { Route as StellestKatalogSLinzamiRouteImport } from './routes/stellest-katalog-s-linzami'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequisitesRouteImport } from './routes/requisites'
import { Route as RemontOchkovRouteImport } from './routes/remont-ochkov'
import { Route as PolitikaKonfidentsialnostiRouteImport } from './routes/politika-konfidentsialnosti'
import { Route as PodborOchkovRouteImport } from './routes/podbor-ochkov'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as MainV2RouteImport } from './routes/main-v2'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as KabinetDiagnostikiSpbRouteImport } from './routes/kabinet-diagnostiki-spb'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UslugiSlugRouteImport } from './routes/uslugi.$slug'
import { Route as Catalog_sCategoryRouteImport } from './routes/catalog_s.$category'
import { Route as BlogCategoryRouteImport } from './routes/blog.$category'
import { Route as Catalog_sCategoryIndexRouteImport } from './routes/catalog_s.$category.index'
import { Route as BlogCategoryIndexRouteImport } from './routes/blog.$category.index'
import { Route as Catalog_sCategorySlugRouteImport } from './routes/catalog_s.$category.$slug'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.$category.$slug'
import { Route as BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRouteImport } from './routes/blog.linzy-dlya-ochkov.pokrytiya-linz-dlya-ochkov.index'

const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const TinkoffRoute = TinkoffRouteImport.update({
  id: '/tinkoff',
  path: '/tinkoff',
  getParentRoute: () => rootRouteImport,
} as any)
const StellestKatalogSLinzamiRoute = StellestKatalogSLinzamiRouteImport.update({
  id: '/stellest-katalog-s-linzami',
  path: '/stellest-katalog-s-linzami',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitesRoute = RequisitesRouteImport.update({
  id: '/requisites',
  path: '/requisites',
  getParentRoute: () => rootRouteImport,
} as any)
const RemontOchkovRoute = RemontOchkovRouteImport.update({
  id: '/remont-ochkov',
  path: '/remont-ochkov',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaKonfidentsialnostiRoute =
  PolitikaKonfidentsialnostiRouteImport.update({
    id: '/politika-konfidentsialnosti',
    path: '/politika-konfidentsialnosti',
    getParentRoute: () => rootRouteImport,
  } as any)
const PodborOchkovRoute = PodborOchkovRouteImport.update({
  id: '/podbor-ochkov',
  path: '/podbor-ochkov',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const MainV2Route = MainV2RouteImport.update({
  id: '/main-v2',
  path: '/main-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const KabinetDiagnostikiSpbRoute = KabinetDiagnostikiSpbRouteImport.update({
  id: '/kabinet-diagnostiki-spb',
  path: '/kabinet-diagnostiki-spb',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const UslugiSlugRoute = UslugiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UslugiRoute,
} as any)
const Catalog_sCategoryRoute = Catalog_sCategoryRouteImport.update({
  id: '/catalog_s/$category',
  path: '/catalog_s/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryRoute = BlogCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => BlogRoute,
} as any)
const Catalog_sCategoryIndexRoute = Catalog_sCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Catalog_sCategoryRoute,
} as any)
const BlogCategoryIndexRoute = BlogCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogCategoryRoute,
} as any)
const Catalog_sCategorySlugRoute = Catalog_sCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => Catalog_sCategoryRoute,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogCategoryRoute,
} as any)
const BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRoute =
  BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRouteImport.update({
    id: '/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov/',
    path: '/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov/',
    getParentRoute: () => BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basket': typeof BasketRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/kabinet-diagnostiki-spb': typeof KabinetDiagnostikiSpbRoute
  '/loyalty': typeof LoyaltyRoute
  '/main-v2': typeof MainV2Route
  '/o-nas': typeof ONasRoute
  '/payment': typeof PaymentRoute
  '/personal': typeof PersonalRoute
  '/podbor-ochkov': typeof PodborOchkovRoute
  '/politika-konfidentsialnosti': typeof PolitikaKonfidentsialnostiRoute
  '/remont-ochkov': typeof RemontOchkovRoute
  '/requisites': typeof RequisitesRoute
  '/search': typeof SearchRoute
  '/stellest-katalog-s-linzami': typeof StellestKatalogSLinzamiRoute
  '/tinkoff': typeof TinkoffRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/blog/$category': typeof BlogCategoryRouteWithChildren
  '/catalog_s/$category': typeof Catalog_sCategoryRouteWithChildren
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/catalog_s/$category/$slug': typeof Catalog_sCategorySlugRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
  '/catalog_s/$category/': typeof Catalog_sCategoryIndexRoute
  '/blog/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov/': typeof BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/kabinet-diagnostiki-spb': typeof KabinetDiagnostikiSpbRoute
  '/loyalty': typeof LoyaltyRoute
  '/main-v2': typeof MainV2Route
  '/o-nas': typeof ONasRoute
  '/payment': typeof PaymentRoute
  '/personal': typeof PersonalRoute
  '/podbor-ochkov': typeof PodborOchkovRoute
  '/politika-konfidentsialnosti': typeof PolitikaKonfidentsialnostiRoute
  '/remont-ochkov': typeof RemontOchkovRoute
  '/requisites': typeof RequisitesRoute
  '/search': typeof SearchRoute
  '/stellest-katalog-s-linzami': typeof StellestKatalogSLinzamiRoute
  '/tinkoff': typeof TinkoffRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/catalog_s/$category/$slug': typeof Catalog_sCategorySlugRoute
  '/blog/$category': typeof BlogCategoryIndexRoute
  '/catalog_s/$category': typeof Catalog_sCategoryIndexRoute
  '/blog/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov': typeof BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basket': typeof BasketRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contacts': typeof ContactsRoute
  '/kabinet-diagnostiki-spb': typeof KabinetDiagnostikiSpbRoute
  '/loyalty': typeof LoyaltyRoute
  '/main-v2': typeof MainV2Route
  '/o-nas': typeof ONasRoute
  '/payment': typeof PaymentRoute
  '/personal': typeof PersonalRoute
  '/podbor-ochkov': typeof PodborOchkovRoute
  '/politika-konfidentsialnosti': typeof PolitikaKonfidentsialnostiRoute
  '/remont-ochkov': typeof RemontOchkovRoute
  '/requisites': typeof RequisitesRoute
  '/search': typeof SearchRoute
  '/stellest-katalog-s-linzami': typeof StellestKatalogSLinzamiRoute
  '/tinkoff': typeof TinkoffRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/blog/$category': typeof BlogCategoryRouteWithChildren
  '/catalog_s/$category': typeof Catalog_sCategoryRouteWithChildren
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/catalog_s/$category/$slug': typeof Catalog_sCategorySlugRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
  '/catalog_s/$category/': typeof Catalog_sCategoryIndexRoute
  '/blog/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov/': typeof BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basket'
    | '/blog'
    | '/checkout'
    | '/contacts'
    | '/kabinet-diagnostiki-spb'
    | '/loyalty'
    | '/main-v2'
    | '/o-nas'
    | '/payment'
    | '/personal'
    | '/podbor-ochkov'
    | '/politika-konfidentsialnosti'
    | '/remont-ochkov'
    | '/requisites'
    | '/search'
    | '/stellest-katalog-s-linzami'
    | '/tinkoff'
    | '/uslugi'
    | '/blog/$category'
    | '/catalog_s/$category'
    | '/uslugi/$slug'
    | '/blog/'
    | '/blog/$category/$slug'
    | '/catalog_s/$category/$slug'
    | '/blog/$category/'
    | '/catalog_s/$category/'
    | '/blog/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basket'
    | '/checkout'
    | '/contacts'
    | '/kabinet-diagnostiki-spb'
    | '/loyalty'
    | '/main-v2'
    | '/o-nas'
    | '/payment'
    | '/personal'
    | '/podbor-ochkov'
    | '/politika-konfidentsialnosti'
    | '/remont-ochkov'
    | '/requisites'
    | '/search'
    | '/stellest-katalog-s-linzami'
    | '/tinkoff'
    | '/uslugi'
    | '/uslugi/$slug'
    | '/blog'
    | '/blog/$category/$slug'
    | '/catalog_s/$category/$slug'
    | '/blog/$category'
    | '/catalog_s/$category'
    | '/blog/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov'
  id:
    | '__root__'
    | '/'
    | '/basket'
    | '/blog'
    | '/checkout'
    | '/contacts'
    | '/kabinet-diagnostiki-spb'
    | '/loyalty'
    | '/main-v2'
    | '/o-nas'
    | '/payment'
    | '/personal'
    | '/podbor-ochkov'
    | '/politika-konfidentsialnosti'
    | '/remont-ochkov'
    | '/requisites'
    | '/search'
    | '/stellest-katalog-s-linzami'
    | '/tinkoff'
    | '/uslugi'
    | '/blog/$category'
    | '/catalog_s/$category'
    | '/uslugi/$slug'
    | '/blog/'
    | '/blog/$category/$slug'
    | '/catalog_s/$category/$slug'
    | '/blog/$category/'
    | '/catalog_s/$category/'
    | '/blog/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasketRoute: typeof BasketRoute
  BlogRoute: typeof BlogRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactsRoute: typeof ContactsRoute
  KabinetDiagnostikiSpbRoute: typeof KabinetDiagnostikiSpbRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MainV2Route: typeof MainV2Route
  ONasRoute: typeof ONasRoute
  PaymentRoute: typeof PaymentRoute
  PersonalRoute: typeof PersonalRoute
  PodborOchkovRoute: typeof PodborOchkovRoute
  PolitikaKonfidentsialnostiRoute: typeof PolitikaKonfidentsialnostiRoute
  RemontOchkovRoute: typeof RemontOchkovRoute
  RequisitesRoute: typeof RequisitesRoute
  SearchRoute: typeof SearchRoute
  StellestKatalogSLinzamiRoute: typeof StellestKatalogSLinzamiRoute
  TinkoffRoute: typeof TinkoffRoute
  UslugiRoute: typeof UslugiRouteWithChildren
  Catalog_sCategoryRoute: typeof Catalog_sCategoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tinkoff': {
      id: '/tinkoff'
      path: '/tinkoff'
      fullPath: '/tinkoff'
      preLoaderRoute: typeof TinkoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stellest-katalog-s-linzami': {
      id: '/stellest-katalog-s-linzami'
      path: '/stellest-katalog-s-linzami'
      fullPath: '/stellest-katalog-s-linzami'
      preLoaderRoute: typeof StellestKatalogSLinzamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisites': {
      id: '/requisites'
      path: '/requisites'
      fullPath: '/requisites'
      preLoaderRoute: typeof RequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remont-ochkov': {
      id: '/remont-ochkov'
      path: '/remont-ochkov'
      fullPath: '/remont-ochkov'
      preLoaderRoute: typeof RemontOchkovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-konfidentsialnosti': {
      id: '/politika-konfidentsialnosti'
      path: '/politika-konfidentsialnosti'
      fullPath: '/politika-konfidentsialnosti'
      preLoaderRoute: typeof PolitikaKonfidentsialnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podbor-ochkov': {
      id: '/podbor-ochkov'
      path: '/podbor-ochkov'
      fullPath: '/podbor-ochkov'
      preLoaderRoute: typeof PodborOchkovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main-v2': {
      id: '/main-v2'
      path: '/main-v2'
      fullPath: '/main-v2'
      preLoaderRoute: typeof MainV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kabinet-diagnostiki-spb': {
      id: '/kabinet-diagnostiki-spb'
      path: '/kabinet-diagnostiki-spb'
      fullPath: '/kabinet-diagnostiki-spb'
      preLoaderRoute: typeof KabinetDiagnostikiSpbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/uslugi/$slug': {
      id: '/uslugi/$slug'
      path: '/$slug'
      fullPath: '/uslugi/$slug'
      preLoaderRoute: typeof UslugiSlugRouteImport
      parentRoute: typeof UslugiRoute
    }
    '/catalog_s/$category': {
      id: '/catalog_s/$category'
      path: '/catalog_s/$category'
      fullPath: '/catalog_s/$category'
      preLoaderRoute: typeof Catalog_sCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category': {
      id: '/blog/$category'
      path: '/$category'
      fullPath: '/blog/$category'
      preLoaderRoute: typeof BlogCategoryRouteImport
      parentRoute: typeof BlogRoute
    }
    '/catalog_s/$category/': {
      id: '/catalog_s/$category/'
      path: '/'
      fullPath: '/catalog_s/$category/'
      preLoaderRoute: typeof Catalog_sCategoryIndexRouteImport
      parentRoute: typeof Catalog_sCategoryRoute
    }
    '/blog/$category/': {
      id: '/blog/$category/'
      path: '/'
      fullPath: '/blog/$category/'
      preLoaderRoute: typeof BlogCategoryIndexRouteImport
      parentRoute: typeof BlogCategoryRoute
    }
    '/catalog_s/$category/$slug': {
      id: '/catalog_s/$category/$slug'
      path: '/$slug'
      fullPath: '/catalog_s/$category/$slug'
      preLoaderRoute: typeof Catalog_sCategorySlugRouteImport
      parentRoute: typeof Catalog_sCategoryRoute
    }
    '/blog/$category/$slug': {
      id: '/blog/$category/$slug'
      path: '/$slug'
      fullPath: '/blog/$category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof BlogCategoryRoute
    }
    '/blog/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov/': {
      id: '/blog/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov/'
      path: '/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov'
      fullPath: '/blog/linzy-dlya-ochkov/pokrytiya-linz-dlya-ochkov/'
      preLoaderRoute: typeof BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogCategoryRouteChildren {
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogCategoryIndexRoute: typeof BlogCategoryIndexRoute
}

const BlogCategoryRouteChildren: BlogCategoryRouteChildren = {
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogCategoryIndexRoute: BlogCategoryIndexRoute,
}

const BlogCategoryRouteWithChildren = BlogCategoryRoute._addFileChildren(
  BlogCategoryRouteChildren,
)

interface BlogRouteChildren {
  BlogCategoryRoute: typeof BlogCategoryRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
  BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRoute: typeof BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogCategoryRoute: BlogCategoryRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
  BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRoute:
    BlogLinzyDlyaOchkovPokrytiyaLinzDlyaOchkovIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface UslugiRouteChildren {
  UslugiSlugRoute: typeof UslugiSlugRoute
}

const UslugiRouteChildren: UslugiRouteChildren = {
  UslugiSlugRoute: UslugiSlugRoute,
}

const UslugiRouteWithChildren =
  UslugiRoute._addFileChildren(UslugiRouteChildren)

interface Catalog_sCategoryRouteChildren {
  Catalog_sCategorySlugRoute: typeof Catalog_sCategorySlugRoute
  Catalog_sCategoryIndexRoute: typeof Catalog_sCategoryIndexRoute
}

const Catalog_sCategoryRouteChildren: Catalog_sCategoryRouteChildren = {
  Catalog_sCategorySlugRoute: Catalog_sCategorySlugRoute,
  Catalog_sCategoryIndexRoute: Catalog_sCategoryIndexRoute,
}

const Catalog_sCategoryRouteWithChildren =
  Catalog_sCategoryRoute._addFileChildren(Catalog_sCategoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasketRoute: BasketRoute,
  BlogRoute: BlogRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactsRoute: ContactsRoute,
  KabinetDiagnostikiSpbRoute: KabinetDiagnostikiSpbRoute,
  LoyaltyRoute: LoyaltyRoute,
  MainV2Route: MainV2Route,
  ONasRoute: ONasRoute,
  PaymentRoute: PaymentRoute,
  PersonalRoute: PersonalRoute,
  PodborOchkovRoute: PodborOchkovRoute,
  PolitikaKonfidentsialnostiRoute: PolitikaKonfidentsialnostiRoute,
  RemontOchkovRoute: RemontOchkovRoute,
  RequisitesRoute: RequisitesRoute,
  SearchRoute: SearchRoute,
  StellestKatalogSLinzamiRoute: StellestKatalogSLinzamiRoute,
  TinkoffRoute: TinkoffRoute,
  UslugiRoute: UslugiRouteWithChildren,
  Catalog_sCategoryRoute: Catalog_sCategoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
